package com.serkan.jpa;
// Generated 8 avr. 2016 09:15:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppInstance generated by hbm2java
 */
@Entity
@Table(name = "app_instance", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "app_instance_cd") )
public class AppInstance implements java.io.Serializable
{
   
   private long appInstanceId;
   private String appInstanceCd;
   private String appInstanceLb;
   private String appInstanceJmxUrl;
   private String appInstanceType;
   private Set<DtaCustomer> dtaCustomers = new HashSet<DtaCustomer>(0);
   
   public AppInstance()
   {
   }
   
   public AppInstance(long appInstanceId, String appInstanceCd)
   {
      this.appInstanceId = appInstanceId;
      this.appInstanceCd = appInstanceCd;
   }
   
   public AppInstance(long appInstanceId, String appInstanceCd, String appInstanceLb, String appInstanceJmxUrl, String appInstanceType, Set<DtaCustomer> dtaCustomers)
   {
      this.appInstanceId = appInstanceId;
      this.appInstanceCd = appInstanceCd;
      this.appInstanceLb = appInstanceLb;
      this.appInstanceJmxUrl = appInstanceJmxUrl;
      this.appInstanceType = appInstanceType;
      this.dtaCustomers = dtaCustomers;
   }
   
   public AppInstance(String appInstanceCd, String appInstanceLb)
   {
      this.appInstanceCd = appInstanceCd;
      this.appInstanceLb = appInstanceLb;
   }
   
   @Id
   @SequenceGenerator(name="app_seq", sequenceName="app_instance_seq", allocationSize=1)
   @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="app_seq")
   @Column(name = "app_instance_id", unique = true, nullable = false)
   public long getAppInstanceId()
   {
      return this.appInstanceId;
   }
   
   public void setAppInstanceId(long appInstanceId)
   {
      this.appInstanceId = appInstanceId;
   }
   
   @Column(name = "app_instance_cd", unique = true, nullable = false, length = 128)
   public String getAppInstanceCd()
   {
      return this.appInstanceCd;
   }
   
   public void setAppInstanceCd(String appInstanceCd)
   {
      this.appInstanceCd = appInstanceCd;
   }
   
   @Column(name = "app_instance_lb", length = 128)
   public String getAppInstanceLb()
   {
      return this.appInstanceLb;
   }
   
   public void setAppInstanceLb(String appInstanceLb)
   {
      this.appInstanceLb = appInstanceLb;
   }
   
   @Column(name = "app_instance_jmx_url", length = 256)
   public String getAppInstanceJmxUrl()
   {
      return this.appInstanceJmxUrl;
   }
   
   public void setAppInstanceJmxUrl(String appInstanceJmxUrl)
   {
      this.appInstanceJmxUrl = appInstanceJmxUrl;
   }
   
   @Column(name = "app_instance_type", length = 64)
   public String getAppInstanceType()
   {
      return this.appInstanceType;
   }
   
   public void setAppInstanceType(String appInstanceType)
   {
      this.appInstanceType = appInstanceType;
   }
   
   @OneToMany(fetch = FetchType.LAZY, mappedBy = "appInstance")
   public Set<DtaCustomer> getDtaCustomers()
   {
      return this.dtaCustomers;
   }
   
   public void setDtaCustomers(Set<DtaCustomer> dtaCustomers)
   {
      this.dtaCustomers = dtaCustomers;
   }
   
}
